INSERT INTO `lang_strings`(`language`, `label`, `text`) VALUES
(2,'modal-label-logSignin','Inicia sesión o crea una cuenta'),
(1,'modal-label-logSignin','Log in or Sign in'),
(2,'modal-label-login','Entra en tu cuenta.'),
(1,'modal-label-login','Log in.'),
(2,'modal-label-email-placeholder','Tu email...'),
(1,'modal-label-email-placeholder','Your email...'),
(2,'modal-label-pass-placeholder','Tu contraseña...'),
(1,'modal-label-pass-placeholder','Your password...'),
(2,'modal-label-login-button','Iniciar'),
(1,'modal-label-login-button','Log in'),
(2,'modal-label-login-button-forget','¿Olvidaste la contraseña?'),
(1,'modal-label-login-button-forget','Do you forgot your password?'),
(2,'modal-label-signin','Crear cuenta.'),
(1,'modal-label-signin','Sign in.'),
(2,'modal-label-tooltip','Crea tu cuenta para acceder a la información de los eventos. Es gratis y sencillo.'),
(1,'modal-label-tooltip',"Sign in to access to the info about events.It's free and simple."),
(2,'modal-label-name-placeholder','Tu nombre...'),
(1,'modal-label-name-placeholder','Your name...'),
(2,'modal-label-terms','Acepto los términos de registro.'),
(1,'modal-label-terms','I accept the terms of registration'),
(2,'modal-label-create-account','Crear cuenta.'),
(1,'modal-label-create-account','Create a account.'),
(2,'modal-label-info','*Puedes agilizar el registro usando directamente tu cuenta de Facebook.'),
(1,'modal-label-info','*You can make the registration easier using your Facebook directly.'),
(2,'header-logged-admin','Administar'),
(1,'header-logged-admin','dashboard'),
(2,'header-logged-profile','Mi perfil'),
(1,'header-logged-profile','My profile'),
(2,'label-log-out','Desconectarse'),
(1,'label-log-out','Log out'),
(2,'header-create-event','Crear evento'),
(1,'header-create-event','Create event'),
(2,'how-it-works','Como funciona'),
(1,'how-it-works','How it works'),
(2,'label-search','Buscar'),
(1,'label-search','Search'),
(2,'header-my-account','Mi cuenta'),
(1,'header-my-account','My account')